version: '3.8'

services:
  app:
    build: .
    working_dir: /var/www
    container_name: prep_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - prep

  nginx:
    image: nginx:alpine
    container_name: prep_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - prep

  db:
    image: postgres:15
    container_name: prep_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: prep
      POSTGRES_USER: prep
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - prep
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: prep_redis
    ports:
      - "6379:6379"
    networks:
      - prep
    volumes:
      - redis_data:/data

  queue:
    build: .
    container_name: prep_queue
    working_dir: /var/www
    command: php artisan queue:work --tries=3
    volumes:
     - .:/var/www
    depends_on:
      - redis
      - app
    networks:
      - prep

  scheduler:
    build: .
    container_name: prep_scheduler
    working_dir: /var/www
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - prep

networks:
  prep:

volumes:
  pgdata:
  redis_data:
